config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  get '/saml/auth' => 'saml_idp#new'
  post '/saml/auth' => 'saml_idp#create'
  get '/saml/logout' => 'saml_idp#logout'

  resources :users
  get '/sp_edit' => 'users#sp_edit'
  get '/signin' => 'users#sign_in', as: :signin
  post '/signin' => 'users#create_session'
  get '/signout' => 'users#sign_out', as: :signout

  get '/signup' => 'users#new'

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_uniqueness_of :email

  def signed_in?
    logged_in
  end
end

app/controllers/users_controller.rb
require 'uuid'

class UsersController < ApplicationController
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]

  def new
    @user = User.new
    session[:forwarding_url] = params[:login_url]
  end

  def edit
  end

  def sign_in
    @user = User.new
    #@email = params[:email]
    session[:forwarding_url] = params[:login_url]
  end

  def create_session
    user = User.where(:email => params[:email]).first
    user && user.authenticate(params[:password]) ? user : nil
    session[:user_id] = user.email
    user.logged_in = true
    user.current_logged_in_at = Time.now
    user.save
    redirect_to root_path
  end

  def sign_out
    user = User.where(email: params[:email]).first
    #session[:user_id] = user.email
    user.logged_in = false
    user.current_logged_in_at = nil
    user.save
    redirect_to root_path, notice: 'User logged out'
  end

  def sp_edit
    @user = User.where(email: params[:user_id]).first
    render :edit
  end

  def show
  end

  def create
    @user = User.new(user_profile_parameters)
    @user.uid = UUID.generate
    if @user.save
      flash[:notice] = "#{@user.email} signed in."
      redirect_to(session[:forwarding_url] || root_path)
      session.delete(:forwarding_url)
    else
      render "new"
    end
  end

  def update
    @user.update_attributes(user_profile_parameters)

    respond_to do |format|
      if @user.save
        format.html do
          if params[:sp_profile_url]
            redirect_to params[:sp_profile_url] + "?first_name=#{params[:user][:first_name]}&last_name=#{params[:user][:last_name]}"
          else
            redirect_to user_path(@user), notice: 'Profile was successfully updated.'
          end
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_profile_parameters
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :login_url)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
.form-horizontal
  = semantic_form_for  @user do |f|
    = hidden_field_tag "sp_profile_url", params[:profile_url]
    .col-md-6
      - if @user.errors.any?
        .error_messages
          %h2 Form is invalid
          %ul
            - for message in @user.errors.full_messages
              %li= message
      .fieldset
        = f.inputs do
          = f.input :first_name
          = f.input :last_name
          = f.input :email
          = f.input :password
          = f.input :password_confirmation

      .actions
        = f.submit 'Save'

app/views/users/edit.html.haml
.containier
  %h1 Edit profile for #{@user.email}

  = render 'form'

  /= link_to 'Back', profiles_path

app/views/users/new.html.haml
%h1 Sign Up
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions= f.submit

app/views/users/show.html.haml
.container
  %p#notice= notice

  %h3
    User: #{@user.email}
    - if @user.signed_in?
      %span.online Online since #{@user.current_logged_in_at.localtime}
      = link_to 'Sign out', signout_path(email: @user.email)
    - else
      = link_to 'Sign in', signin_path(email: @user.email)

  %p
    %b Firstname:
    = @user.first_name
  %p
    %b Lastname:
    = @user.last_name

  = link_to 'Edit', edit_user_path(@user)
  \|
  = link_to 'Back', root_path

  %p= link_to 'Destroy', @user, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/users/sign_in.html.haml
.container
  %h2 Sign In
  - if @saml_idp_fail_msg
    #saml_idp_fail_msg.flash.error= @saml_idp_fail_msg
  = form_tag '/signin' do
    %p
      = label_tag :email
      = email_field_tag :email, params[:email], :autocapitalize => "off", :autocorrect => "off", :autofocus => "autofocus", :spellcheck => "false", :size => 30, :class => "email_pwd txt"
    %p
      = label_tag :password
      = password_field_tag :password, params[:password], :autocapitalize => "off", :autocorrect => "off", :spellcheck => "false", :size => 30, :class => "email_pwd txt"
    %p
      = submit_tag "Sign in", :class => "button big blueish"